### ISSUE TITLE
Incomplete translation in original book

### ISSUE THREAD

**Issue by rmyorston** [standardebooks/seneca_dialogues_aubrey-stewart#2]
In To Polybius, On Consolation Chapter 5 there is this text:

> if you possibly can, cast out conceal it within you and hide it away so that it may not be seen

Clearly there's something not quite right about that. The [original Latin](http://www.thelatinlibrary.com/sen/sen.consolatione1.shtml) is:

> si potes, proice omnem ex toto dolorem, si minus, introrsus abde et contine, ne appareat

'si potes' is 'if you can'; 'proice' is the imperative 'cast out'; 'introrsus abde' is 'conceal within you'. So it appears that the translation for 'omnem ex toto dolorem, si minus' has somehow been omitted.

Now, it's many years since I've had to do any translation from Latin, but I still have my dictionary and grammar.  Also, we have examples from Stewart.

The construction 'si potes, ... , si minus' is similar to this from On Benefits Book 2 Chapter 14:

> si potero, reuocabo, si minus, non adiuuabo scelus

which is (somewhat verbosely) translated as:

> if possible, I will restrain men from crime; if not, at least I will never assist them in it

So 'si minus' is just 'if not'.

'dolorem' is translated as 'grief' earlier in Polybius Chapter 5 ('dismiss the grief which affects you both') and 'omnem' agrees with 'dolorem', so that's 'all grief'.

In On Peace of Mind Chapter 10 Stewart translates

> quoniam includi ex toto non patiuntur

as

> since they will not endure to be altogether locked up

So 'ex toto' is making the statement more emphatic. Having 'altogether' and 'all grief' is inelegant, so let's say 'completely' instead.

My suggested translation is thus:

> if you possibly can, cast out [completely all of your grief; if not,] conceal it within you and hide it away so that it may not be seen

**Comment by acabal** [comment]
Hi there, this is an excellent analysis, thanks!

Normally I would be very, very hesitant about altering the text of a translation. But in this case, since the original is clearly ungrammatical English as printed, I think it's most likely that the missing subclause in the print edition is simply a printer's typo. So, I'm OK with adding your correction as suggested.

(I actually remember marking this sentence for review when proofing this edition. I was surprised to find that the transcription was accurate, and left it as such since I have no experience with Latin and since this translation is already fairly awkward in general.)

I'll make a note of the change in the production notes metadata. This is fixed in ed58377. Thanks!
